[build]
  publish = "_site"
  command = "npm run build"

# Redirect Netlify subdomain
[[redirects]]
  from = "https://a11yweekly.netlify.app/*"
  to = "https://a11yweekly.com"
  status = 301
  force = true

[[redirects]]
  from = "http://a11yweekly.netlify.app/*"
  to = "https://a11yweekly.com"
  status = 301
  force = true

[[redirects]]
  from = "https://www.a11yweekly.netlify.app/*"
  to = "https://a11yweekly.com"
  status = 301
  force = true

[[redirects]]
  from = "http://www.a11yweekly.netlify.app/*"
  to = "https://a11yweekly.com"
  status = 301
  force = true

# Redirect feed url
[[redirects]]
  from = "/feed"
  to = "/feed/index.xml"
  status = 200
  force = true

# Header best practices
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "form-action https:"
    Feature-Policy = "vibrate 'none'; geolocation 'none'; midi 'none'; notifications 'none'; push 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; fullscreen 'none'; payment 'none'"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"